title: "Duo Multicultural Arts Center"
tagline: "DMAC is a multicultural arts center for independent artists in the heart of the East Village."
baseurl: /duo
plugins:
  - jekyll-postcss-v2
  - jekyll-seo-tag
collections:
  work:
    output: true
prose:
  siteurl: 'http://joebabbitt.com/duo/'
  media: 'assets/uploaded'
  ignore:
    - "works.html"
    - "_config.yml"
    - "/_layouts"
    - "/_includes"
    - "/.github"
    - ".gitignore"
    - "Gemfile"
    - "package.json"
    - "package-lock.json"
    - "postcss.config.js"
    - "tailwind.config.js"
  metadata:
    '':
      - name: "layout"
        field:
          element: "hidden"
          value: "default"
      - name: "current_status"
        field:
          label: "Current Status"
          element: "select"
          options:
            - "Coming soon"
            - "In previews"
            - "Currently playing"
            - "Extended!"
            - "Last production"
            - " "
      - name: "production"
        field:
          element: "text"
          label: "Related Production"
          placeholder: "Enter the title of the related production"
      - name: "description"
        field:
          label: "Page Description"
          element: "textarea"
          help: "Enter a longform description for the page"
    _work:
      - name: "layout"
        field:
          element: "hidden"
          value: "work"
      - name: "title"
        field:
          label: "Title"
          element: "text"
      - name: "opening_night"
        field:
          label: "Opening Night"
          element: "text"
          help: "Enter date in YYYY-MM-DD format"
      - name: "closing_night"
        field:
          label: "Closing Night"
          element: "text"
          help: "Enter date in YYYY-MM-DD format"
      - name: "production_company"
        field:
          label: "Production Company"
          element: "text"
      - name: "primary_color"
        field:
          label: "Primary Color"
          help: "Hex code for a primary color for the work"
          placeholder: "#000000"
          element: "color"
      - name: "secondary_color"
        field:
          label: "Secondary Color"
          help: "Hex code for a secondary color for the work"
          placeholder: "#FFFFFF"
          element: "color"
      - name: "image"
        field:
          label: "Poster Image"
          help: "A path to the poster for the work."
          placeholder: "/assets/img/xxxx.jpg"
          element: "image"
      - name: "site"
        field:
          label: "Website URL"
          help: "A website to learn more (optional)"
          element: "text"
      - name: "tickets"
        field:
          label: "Tickets URL"
          help: "A website to get tickets (optional)"
          element: "text"
      - name: "duration"
        field:
          label: "Duration"
          help: "Duration of the performance"
          element: "text"
          placeholder: "1h 30m"
      - name: "hide"
        field:
          label: "Hide on 'Productions' tab"
          element: "checkbox"
          size: "small"
